import type { CollectionRef, DocStore } from '../ports/store.js';

/** Table name (schema.ts pgTable id) → Firestore collection. Identity map today,
 *  but the single place to rename if a collection name must diverge. */
export const COLLECTIONS = {
  organizations: 'organizations',
  org_members: 'org_members',
  org_invitations: 'org_invitations',
  assistants: 'assistants',
  projects: 'projects',
  project_members: 'project_members',
  project_repos: 'project_repos',
  github_repo_catalog: 'github_repo_catalog',
  github_catalog_sync: 'github_catalog_sync',
  gitlab_repo_catalog: 'gitlab_repo_catalog',
  gitlab_catalog_sync: 'gitlab_catalog_sync',
  users: 'users',
  api_keys: 'api_keys',
  global_settings: 'global_settings',
  message_queue: 'message_queue',
  breaker_state: 'breaker_state',
  org_model_keys: 'org_model_keys',
  org_integrations: 'org_integrations',
  integration_install_states: 'integration_install_states',
  integration_events: 'integration_events',
  conversations: 'conversations',
  conversation_messages: 'conversation_messages',
  slack_channel_bindings: 'slack_channel_bindings',
  teams_channel_bindings: 'teams_channel_bindings',
  operations: 'operations',
  team_proposals: 'team_proposals',
  agent_memories: 'agent_memories',
  agent_skills: 'agent_skills',
  assistant_skills: 'assistant_skills',
  gcp_connections: 'gcp_connections',
  gcp_targets: 'gcp_targets',
  gcp_project_connections: 'gcp_project_connections',
  cloudflare_connections: 'cloudflare_connections',
  cloudflare_targets: 'cloudflare_targets',
  cloudflare_project_connections: 'cloudflare_project_connections',
  sentry_connections: 'sentry_connections',
  sentry_targets: 'sentry_targets',
  sentry_project_connections: 'sentry_project_connections',
  grafana_connections: 'grafana_connections',
  grafana_targets: 'grafana_targets',
  grafana_project_connections: 'grafana_project_connections',
  aws_connections: 'aws_connections',
  aws_targets: 'aws_targets',
  azure_connections: 'azure_connections',
  azure_targets: 'azure_targets',
  datadog_connections: 'datadog_connections',
  datadog_targets: 'datadog_targets',
  dynatrace_connections: 'dynatrace_connections',
  dynatrace_targets: 'dynatrace_targets',
  pagerduty_connections: 'pagerduty_connections',
  pagerduty_targets: 'pagerduty_targets',
  traces: 'traces',
  trace_steps: 'trace_steps',
  agent_runs: 'agent_runs',
  mcp_servers: 'mcp_servers',
  kg_builds: 'kg_builds',
  kg_nodes: 'kg_nodes',
  kg_edges: 'kg_edges',
  kg_node_embeddings: 'kg_node_embeddings',
  model_invocations: 'model_invocations',
  /** Internal: per-lane monotonic seq counters (replaces pg_advisory_xact_lock). */
  lanes: 'lanes',
  copilot_issue_offers: 'copilot_issue_offers',
  conversation_reports: 'conversation_reports',
  report_offers: 'report_offers',
  /** Dedicated KNN points for FirestoreVectorIndex: embedding + flattened restrict fields. */
  vector_points: 'vector_points',
  org_billing_usage: 'org_billing_usage',
  credit_ledger: 'credit_ledger',
  fx_rates: 'fx_rates',
} as const;

export type CollectionName = keyof typeof COLLECTIONS;

/** Typed handle to a root collection over the DocStore port. */
export function col(store: DocStore, name: CollectionName): CollectionRef {
  return store.collection(COLLECTIONS[name]);
}
