import { sql } from 'drizzle-orm';
import { bigint, boolean, index, integer, jsonb, numeric, pgEnum, pgTable, primaryKey, real, text, timestamp, uniqueIndex, uuid, vector, type AnyPgColumn } from 'drizzle-orm/pg-core';
import type { TeamProposalDoc } from '../team/proposal-schema.js';

export const memberRole = pgEnum('member_role', ['owner', 'manager', 'user']);

export const organizations = pgTable('organizations', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  plan: text('plan').notNull().default('free'),
  // Realm lifecycle: 'pending' = signup recorded, realm not yet provisioned;
  // 'active' = realm + owner exist. Pending rows reserve the slug.
  status: text('status').notNull().default('active'),
  // Secret of the per-realm 'app' OIDC client (generated by us at provisioning).
  oidcClientSecret: text('oidc_client_secret'),
  // Identity Platform tenant for this org (replaces the Keycloak realm). Null
  // until provisioned; set at signup completion.
  idpTenantId: text('idp_tenant_id'),
  // Per-org federated SSO. ssoProvider is the Identity Platform provider id
  // (e.g. 'saml.acme-okta' / 'oidc.acme-entra'); null = password-only.
  ssoProvider: text('sso_provider'),
  ssoEnabled: boolean('sso_enabled').notNull().default(false),
  // Email that founded a pending org — lets the same signer re-request the verify
  // email; cleared on activation.
  pendingEmail: text('pending_email'),
  // Beta orgs get access to everything for free (bypasses plan limits once
  // enforcement exists; only stored/toggled for now — see super-ui spec).
  betaTester: boolean('beta_tester').notNull().default(false),
  // Knowledge Graph feature flag — org-scoped, off by default, toggled only in
  // the super console. Gates the project KG tab + its HTTP routes.
  kgEnabled: boolean('kg_enabled').notNull().default(false),
  // Hindsight agent flag — org-admin opt-in. When on: post-turn summaries are
  // produced and the system Hindsight agent is offerable for delegation.
  hindsightEnabled: boolean('hindsight_enabled').notNull().default(false),
  // Cost visibility flag — org-admin opt-in. When on: incident cost USD is shown
  // to org members (e.g. in the incident forecast banner).
  showCostUsd: boolean('show_cost_usd').notNull().default(false),
  // Debug flag — super-console toggle. When on: members see the fully-assembled
  // system prompt (persona + RCA preamble + integration skills) in the assistant
  // editor and team-proposal review, via the preview-prompt endpoint.
  debugEnabled: boolean('debug_enabled').notNull().default(false),
  approvalPolicy: jsonb('approval_policy').$type<{ writeToolsRequireApproval: boolean; overrides?: Record<string, boolean> } | null>(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const orgMembers = pgTable(
  'org_members',
  {
    orgId: uuid('org_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
    userId: text('user_id').notNull(), // Keycloak subject
    role: memberRole('role').notNull().default('user'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('org_members_org_user').on(t.orgId, t.userId)],
);

export const inviteStatus = pgEnum('invite_status', ['pending', 'accepted', 'revoked']);

export const orgInvitations = pgTable(
  'org_invitations',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orgId: uuid('org_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
    email: text('email').notNull(), // always lowercased
    role: memberRole('role').notNull(), // 'manager' | 'user' only (enforced at the API layer)
    invitedBy: text('invited_by').notNull(), // Keycloak subject of the inviter
    status: inviteStatus('status').notNull().default('pending'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  },
  (t) => [
    // At most one PENDING invite per (org, email); accepted/revoked rows don't block re-inviting.
    uniqueIndex('org_invitations_pending').on(t.orgId, t.email).where(sql`status = 'pending'`),
    index('org_invitations_org').on(t.orgId),
  ],
);

export const assistants = pgTable(
  'assistants',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    projectId: uuid('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    persona: text('persona').notNull().default(''),
    model: text('model').notNull().default('gemini-3-flash-preview'),
    provider: text('provider'),  // 'platform'|'anthropic'|'openai'|'google'|'openai-compatible'; null = resolve from catalog
    enabledTools: jsonb('enabled_tools').$type<string[]>().notNull().default([]),
    isLead: boolean('is_lead').notNull().default(false),
    // Origin tracking for AI-designed teams: set when an agent is created by autogen
    // (points at the team_proposals version that produced it); null = manually created.
    sourceProposalId: uuid('source_proposal_id').references((): AnyPgColumn => teamProposals.id, { onDelete: 'set null' }),
    // True once a user edits an autogen-created agent (powers the "edited" badge).
    userModified: boolean('user_modified').notNull().default(false),
    // NOTE: the DB still physically has is_contact_point / tier / escalation_model columns
    // (dead columns, dropped in a later migration once old revisions are gone). They are
    // intentionally omitted from this schema object so Drizzle ignores them.
    graphX: real('graph_x'),
    graphY: real('graph_y'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('assistants_project_id').on(t.projectId)],
);

export const projectRole = pgEnum('project_role', ['admin', 'user']);

export const projects = pgTable(
  'projects',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orgId: uuid('org_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    slug: text('slug').notNull(),
    description: text('description').notNull().default(''),
    approvalPolicy: jsonb('approval_policy').$type<{ writeToolsRequireApproval: boolean; overrides?: Record<string, boolean> } | null>(),
    // The currently-active AI-designed team version (team_proposals.id), or null when the
    // project has no active autogen version (legacy/manual teams).
    activeProposalId: uuid('active_proposal_id').references((): AnyPgColumn => teamProposals.id, { onDelete: 'set null' }),
    // GitHub issue-creation feature flag — project-level opt-in (set by owner/manager).
    issuesEnabled: boolean('issues_enabled').notNull().default(false),
    // Copilot hand-off feature flag — project-level opt-in; requires issuesEnabled.
    copilotEnabled: boolean('copilot_enabled').notNull().default(false),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('projects_org_id').on(t.orgId), uniqueIndex('projects_org_slug').on(t.orgId, t.slug)],
);

export const projectMembers = pgTable(
  'project_members',
  {
    projectId: uuid('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }),
    userId: text('user_id').notNull(),
    role: projectRole('role').notNull().default('user'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('project_members_project_user').on(t.projectId, t.userId)],
);

// A project scopes a subset of an org integration's resources. Per-kind typed
// tables (GitHub repos now; metrics/logs/issues get their own tables later).
export const projectRepos = pgTable(
  'project_repos',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    projectId: uuid('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }),
    orgIntegrationId: uuid('org_integration_id').notNull().references(() => orgIntegrations.id, { onDelete: 'cascade' }),
    repoFullName: text('repo_full_name').notNull(),       // 'owner/name'
    defaultBranch: text('default_branch'),
    // System-resolved code version this project sees for the repo. refType+ref
    // are the configured pin; null falls back to defaultBranch (then repo default).
    refType: text('ref_type'),   // 'branch' | 'commit' | null
    ref: text('ref'),            // branch name or commit SHA; null = use defaultBranch
    addedByUserId: text('added_by_user_id').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('project_repos_project_id').on(t.projectId),
    uniqueIndex('project_repos_project_repo').on(t.projectId, t.repoFullName),
  ],
);

// Per-org-integration cache of the GitHub repos available to connect, so the
// picker is instant. Kept fresh by webhook (repository events) + a 1h-TTL re-sync.
export const githubRepoCatalog = pgTable(
  'github_repo_catalog',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orgIntegrationId: uuid('org_integration_id').notNull().references(() => orgIntegrations.id, { onDelete: 'cascade' }),
    repoFullName: text('repo_full_name').notNull(),
    defaultBranch: text('default_branch'),
    private: boolean('private').notNull().default(false),
    syncedAt: timestamp('synced_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('github_repo_catalog_integration_repo').on(t.orgIntegrationId, t.repoFullName)],
);

// Resumable, poll-advanced catalog sync state. One row per integration. `finishedAt`
// of the last completed pass drives staleness; `nextCursor` is the next GitHub page.
export const githubCatalogSync = pgTable('github_catalog_sync', {
  orgIntegrationId: uuid('org_integration_id').primaryKey().references(() => orgIntegrations.id, { onDelete: 'cascade' }),
  status: text('status').notNull().default('idle'),   // 'idle' | 'syncing' | 'error'
  nextCursor: text('next_cursor'),                      // GitHub page number as text; null at start/end
  repoCount: integer('repo_count').notNull().default(0),
  startedAt: timestamp('started_at', { withTimezone: true }),
  finishedAt: timestamp('finished_at', { withTimezone: true }),
  error: text('error'),
});

export type Project = typeof projects.$inferSelect;
export type ProjectMember = typeof projectMembers.$inferSelect;
export type ProjectRepo = typeof projectRepos.$inferSelect;
export type GithubRepoCatalogRow = typeof githubRepoCatalog.$inferSelect;
export type GithubCatalogSyncRow = typeof githubCatalogSync.$inferSelect;

// Synced from ID-token claims at every login; the email→orgs lookup joins through it.
export const users = pgTable(
  'users',
  {
    userId: text('user_id').primaryKey(), // Keycloak subject
    email: text('email').notNull(), // always lowercased
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('users_email').on(t.email)],
);

// Personal API keys. Scoped to a single org (orgId): the key fully determines
// org scope on the server. Only the sha256 hash is stored — plaintext is shown
// once at creation and never persisted.
export const apiKeys = pgTable(
  'api_keys',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: text('user_id').notNull(), // Keycloak subject of the owner
    orgId: uuid('org_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
    name: text('name').notNull(), // user label, e.g. "CI"
    keyHash: text('key_hash').notNull(), // sha256 hex of the plaintext key
    keyPrefix: text('key_prefix').notNull(), // "bee_xxxxxxxx" (legacy: "ilk_…") — safe to display
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    lastUsedAt: timestamp('last_used_at', { withTimezone: true }),
    revokedAt: timestamp('revoked_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('api_keys_hash').on(t.keyHash),
    index('api_keys_org_user').on(t.orgId, t.userId),
  ],
);

export type ApiKey = typeof apiKeys.$inferSelect;

// Singleton-ish global config rows keyed by name (e.g. 'planLimits').
// Key-value + jsonb so new config categories need no migration.
export const globalSettings = pgTable('global_settings', {
  key: text('key').primaryKey(),
  value: jsonb('value').$type<unknown>().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export type Organization = typeof organizations.$inferSelect;
export type OrgMember = typeof orgMembers.$inferSelect;
export type OrgInvitation = typeof orgInvitations.$inferSelect;
export type Assistant = typeof assistants.$inferSelect;
export type User = typeof users.$inferSelect;
export type GlobalSetting = typeof globalSettings.$inferSelect;

export const queueStatus = pgEnum('queue_status', ['queued', 'running', 'failed', 'cancelled', 'done']);
export const turnSource = pgEnum('turn_source', ['slack', 'teams', 'web', 'api', 'internal']);

// Execution record for one AI turn. The conversation transcript ('turns', a later
// phase) is separate; this table is the durable queue: ordering, status, attempts,
// breaker linkage, cancellation, and visibility all live here.
export const messageQueue = pgTable(
  'message_queue',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    // Ordering / single-flight domain. End-user turns: the conversation id.
    // Internal turns: a caller-derived lane uuid. No FK — conversations are a later phase.
    laneId: uuid('lane_id').notNull(),
    orgId: uuid('org_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
    source: turnSource('source').notNull(),
    seq: bigint('seq', { mode: 'number' }).notNull(), // monotonic per lane
    status: queueStatus('status').notNull().default('queued'),
    payload: jsonb('payload').$type<unknown>().notNull(),
    attempts: integer('attempts').notNull().default(0),
    // Breaker-open deferrals (no provider call). Bounded separately from `attempts` so a long
    // breaker-open window fails the turn cleanly before Pub/Sub dead-letters it.
    deferrals: integer('deferrals').notNull().default(0),
    breakerKey: text('breaker_key'),
    cancelRequested: boolean('cancel_requested').notNull().default(false),
    error: jsonb('error').$type<unknown>(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    startedAt: timestamp('started_at', { withTimezone: true }),
    finishedAt: timestamp('finished_at', { withTimezone: true }),
  },
  (t) => [
    uniqueIndex('message_queue_lane_seq').on(t.laneId, t.seq),
    index('message_queue_lane_status').on(t.laneId, t.status),
    index('message_queue_org').on(t.orgId),
  ],
);

export const breakerStateKind = pgEnum('breaker_state_kind', ['closed', 'open', 'half_open']);

// One row per breaker, keyed "{provider}:{model}:{credentialScope}". Shared across
// instances so the open/half-open state is global, not per-process.
export const breakerState = pgTable('breaker_state', {
  key: text('key').primaryKey(),
  state: breakerStateKind('state').notNull().default('closed'),
  failures: integer('failures').notNull().default(0),
  openedAt: timestamp('opened_at', { withTimezone: true }),
  nextProbeAt: timestamp('next_probe_at', { withTimezone: true }),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export type QueuedTurn = typeof messageQueue.$inferSelect;
export type BreakerRow = typeof breakerState.$inferSelect;

// Per-org BYOK model credentials. One key per (org, provider). Only the AES-GCM
// ciphertext is stored; plaintext is shown once at set time and never returned.
// `enabled` is the explicit per-org opt-in — a stored-but-disabled key stays dormant.
export const orgModelKeys = pgTable(
  'org_model_keys',
  {
    orgId: uuid('org_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
    provider: text('provider').notNull(),        // registry provider id; 'google' = Gemini Developer API
    keyCiphertext: text('key_ciphertext').notNull(),
    keyHint: text('key_hint').notNull(),         // safe-to-display last-4/label
    enabled: boolean('enabled').notNull().default(false),
    baseUrl: text('base_url'),                              // custom openai-compatible endpoint only
    lastTestedAt: timestamp('last_tested_at', { withTimezone: true }),
    lastTestOk: boolean('last_test_ok'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('org_model_keys_org_provider').on(t.orgId, t.provider)],
);

export type OrgModelKey = typeof orgModelKeys.$inferSelect;

// ── Integrations spine ─────────────────────────────────────────────────────
// Provider-agnostic third-party app connections (GitHub now; Slack etc. later).
// One active connection per (org, provider). Provider-specific fields live in
// `metadata`. Secrets (PAT / custom-App PEM) are AES-GCM ciphertext; the
// IntelliLabs Agent App stores NO per-org secret (it uses the global App key +
// the stored installationId).
export const orgIntegrations = pgTable(
  'org_integrations',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orgId: uuid('org_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
    provider: text('provider').notNull(),                 // 'github'
    mode: text('mode').notNull(),                          // github: 'agent_app' | 'pat' | 'custom_app'
    baseUrl: text('base_url'),                             // GHES; null = cloud
    accountLabel: text('account_label'),                   // display, e.g. 'acme-corp'
    secretCiphertext: text('secret_ciphertext'),           // PAT or PEM; null for agent_app
    secretHint: text('secret_hint'),                       // last-4 of a PAT
    metadata: jsonb('metadata').notNull().default(sql`'{}'::jsonb`), // { installationId, appId?, events }
    enabled: boolean('enabled').notNull().default(true),
    lastTestedAt: timestamp('last_tested_at', { withTimezone: true }),
    lastTestOk: boolean('last_test_ok'),
    connectedByUserId: text('connected_by_user_id'),       // session sub (string id)
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('org_integrations_org_provider').on(t.orgId, t.provider)],
);

// Single-use, short-TTL nonces for the install/OAuth callback (CSRF + replay guard).
export const integrationInstallStates = pgTable('integration_install_states', {
  nonce: text('nonce').primaryKey(),
  orgId: uuid('org_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  provider: text('provider').notNull(),
  userId: text('user_id').notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  consumedAt: timestamp('consumed_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

// Durable inbound event log (written by a later plan). Created here so the migration
// is a single unit. `deliveryId` unique = idempotent webhook redelivery.
export const integrationEvents = pgTable(
  'integration_events',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orgId: uuid('org_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
    provider: text('provider').notNull(),
    category: text('category').notNull(),                  // 'issues' | 'pull_requests' | 'branches'
    eventType: text('event_type').notNull(),               // GitHub event name
    action: text('action'),                                // e.g. 'assigned', 'created'
    deliveryId: text('delivery_id').notNull(),
    repoFullName: text('repo_full_name'),
    actorLogin: text('actor_login'),
    mentionsBot: boolean('mentions_bot').notNull().default(false),
    payload: jsonb('payload').notNull(),
    receivedAt: timestamp('received_at', { withTimezone: true }).notNull().defaultNow(),
    processed: boolean('processed').notNull().default(false),
  },
  (t) => [uniqueIndex('integration_events_delivery').on(t.deliveryId)],
);

export type OrgIntegration = typeof orgIntegrations.$inferSelect;
export type IntegrationInstallState = typeof integrationInstallStates.$inferSelect;
export type IntegrationEvent = typeof integrationEvents.$inferSelect;

// ── Conversations (the engine lane = conversation.id). Generic; Slack-populated now. ──
export const conversations = pgTable(
  'conversations',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orgId: uuid('org_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
    projectId: uuid('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }),
    assistantId: uuid('assistant_id').references(() => assistants.id, { onDelete: 'cascade' }),
    rootConversationId: uuid('root_conversation_id'),
    source: text('source').notNull().default('slack'),
    status: text('status').notNull().default('idle'), // 'idle' | 'investigating' | 'done'
    summary: text('summary').notNull().default(''),
    slackChannelId: text('slack_channel_id'),
    slackThreadTs: text('slack_thread_ts'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('conversations_slack_thread').on(t.slackChannelId, t.slackThreadTs),
    index('conversations_root').on(t.rootConversationId),
  ],
);

// Transcript: one row per user/assistant message, monotonic seq per conversation.
export const conversationMessages = pgTable(
  'conversation_messages',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    conversationId: uuid('conversation_id').notNull().references(() => conversations.id, { onDelete: 'cascade' }),
    seq: bigint('seq', { mode: 'number' }).notNull(),
    role: text('role').notNull(),                 // 'user' | 'assistant'
    content: text('content').notNull(),
    slackUserId: text('slack_user_id'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('conversation_messages_seq').on(t.conversationId, t.seq),
    index('conversation_messages_conversation').on(t.conversationId),
  ],
);

// Channel → project+assistant binding. A 'pending' row (null project/assistant) is
// created when the bot is mentioned in an unbound channel; an admin completes it.
export const slackChannelBindings = pgTable(
  'slack_channel_bindings',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orgIntegrationId: uuid('org_integration_id').notNull().references(() => orgIntegrations.id, { onDelete: 'cascade' }),
    slackChannelId: text('slack_channel_id').notNull(),
    channelName: text('channel_name'),
    projectId: uuid('project_id').references(() => projects.id, { onDelete: 'cascade' }),
    // No per-channel assistant: a bound channel routes through the Slack system agent, which
    // delegates to the project's orchestrator. (assistant_id column dropped in 0051.)
    status: text('status').notNull().default('pending'),   // 'pending' | 'bound'
    createdByUserId: text('created_by_user_id'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('slack_channel_bindings_channel').on(t.orgIntegrationId, t.slackChannelId)],
);

export type Conversation = typeof conversations.$inferSelect;
export type ConversationMessage = typeof conversationMessages.$inferSelect;

// ── Operations (internal AI mechanisms: KG builds, embeddings, team-autogen, …) ──
export const operations = pgTable(
  'operations',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orgId: uuid('org_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
    projectId: uuid('project_id'),
    kind: text('kind').notNull(),                 // 'kg-build' | 'embedding' | 'team-autogen' | ...
    parentConversationId: uuid('parent_conversation_id'), // null = top-level; set = nested in an incident
    // The conversation this operation RAN (e.g. the agentic team-gen analysis tree). Inverse of
    // parentConversationId: the conversation is the op's child, so the op stays top-level in the feed.
    runConversationId: uuid('run_conversation_id'),
    refId: uuid('ref_id'),                         // optional link to the domain row (e.g. kg_builds.id)
    status: text('status').notNull().default('running'), // 'running' | 'done' | 'failed'
    costUsd: numeric('cost_usd', { precision: 12, scale: 6 }),
    inputTokens: integer('input_tokens'),
    outputTokens: integer('output_tokens'),
    error: text('error'),
    startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(),
    finishedAt: timestamp('finished_at', { withTimezone: true }),
  },
  (t) => [
    index('operations_org').on(t.orgId),
    index('operations_kind').on(t.kind),
    index('operations_parent').on(t.parentConversationId),
    index('operations_started').on(t.startedAt),
  ],
);
export type Operation = typeof operations.$inferSelect;

// ── Team proposals (AI-designed assistant teams; reviewable draft → apply) ──
export const teamProposals = pgTable(
  'team_proposals',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orgId: uuid('org_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
    projectId: uuid('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }),
    // awaiting_kg | generating | ready | applied | discarded | failed
    status: text('status').notNull().default('awaiting_kg'),
    buildId: uuid('build_id'),                    // KG build the proposal was generated from
    proposal: jsonb('proposal').$type<TeamProposalDoc>(), // null until ready
    facts: jsonb('facts').$type<import('../team/facts.js').Facts>(),
    // Stable display label ("Version N"), assigned per-project when status flips to ready.
    version: integer('version'),
    // Current pipeline phase while status='generating' (a TeamAutogenPhase key); drives the
    // generation progress UI. null until the worker reports the first phase.
    progress: text('progress'),
    error: text('error'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    appliedAt: timestamp('applied_at', { withTimezone: true }),
  },
  (t) => [index('team_proposals_project').on(t.projectId)],
);
export type TeamProposal = typeof teamProposals.$inferSelect;

// ── Agent memories (pgvector; per-project/per-assistant semantic memory store) ──
export const agentMemories = pgTable(
  'agent_memories',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orgId: uuid('org_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
    projectId: uuid('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }),
    assistantId: uuid('assistant_id').references(() => assistants.id, { onDelete: 'cascade' }), // null = team scope
    scope: text('scope').notNull(), // 'private' | 'team'
    content: text('content').notNull(),
    embedding: vector('embedding', { dimensions: 768 }).notNull(),
    usageCount: integer('usage_count').notNull().default(0),
    lastRecalledAt: timestamp('last_recalled_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('agent_memories_project_scope').on(t.projectId, t.scope), index('agent_memories_assistant').on(t.assistantId)],
);
export type AgentMemory = typeof agentMemories.$inferSelect;

// ── Skills (reusable instruction modules; project-level library, attached to assistants) ──
export const agentSkills = pgTable(
  'agent_skills',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orgId: uuid('org_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
    projectId: uuid('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    description: text('description').notNull().default(''),
    body: text('body').notNull().default(''),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('agent_skills_project_name').on(t.projectId, t.name)],
);
export type AgentSkill = typeof agentSkills.$inferSelect;

export const assistantSkills = pgTable(
  'assistant_skills',
  {
    assistantId: uuid('assistant_id').notNull().references(() => assistants.id, { onDelete: 'cascade' }),
    skillId: uuid('skill_id').notNull().references(() => agentSkills.id, { onDelete: 'cascade' }),
  },
  (t) => [primaryKey({ columns: [t.assistantId, t.skillId] })],
);

export type SlackChannelBinding = typeof slackChannelBindings.$inferSelect;

// GCP credentials. projectId null = org-shared (reusable by any project);
// projectId set = project-owned standalone connection. Secrets are AES-GCM ciphertext.
export const gcpConnections = pgTable(
  'gcp_connections',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orgId: uuid('org_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
    projectId: uuid('project_id').references(() => projects.id, { onDelete: 'cascade' }), // null = org-shared
    name: text('name').notNull(),
    mode: text('mode').notNull(),                          // 'sa_key' | 'wif'
    secretCiphertext: text('secret_ciphertext').notNull(),
    secretHint: text('secret_hint'),
    metadata: jsonb('metadata').notNull().default(sql`'{}'::jsonb`), // { saEmail?, defaultGcpProjectId?, availableSignals? }
    enabled: boolean('enabled').notNull().default(true),
    lastTestedAt: timestamp('last_tested_at', { withTimezone: true }),
    lastTestOk: boolean('last_test_ok'),
    createdByUserId: text('created_by_user_id'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('gcp_connections_org').on(t.orgId),
    uniqueIndex('gcp_connections_org_project_name').on(t.orgId, t.projectId, t.name),
  ],
);
export type GcpConnection = typeof gcpConnections.$inferSelect;

// One row per GCP project a Beecause project may query (its SCOPE), via a connection's creds.
// Empty scope for a bound project = unrestricted (any project the SA can reach).
export const gcpTargets = pgTable(
  'gcp_targets',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    projectId: uuid('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }),
    connectionId: uuid('connection_id').notNull().references(() => gcpConnections.id, { onDelete: 'cascade' }),
    gcpProjectId: text('gcp_project_id').notNull(),
    label: text('label'),                                  // optional role, e.g. "Production"
    metadata: jsonb('metadata').notNull().default(sql`'{}'::jsonb`), // { availableSignals }
    addedByUserId: text('added_by_user_id').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('gcp_targets_project_id').on(t.projectId),
    uniqueIndex('gcp_targets_project_gcp').on(t.projectId, t.gcpProjectId),
  ],
);
export type GcpTarget = typeof gcpTargets.$inferSelect;

// A project's single GCP connection binding (mirrors cloudflare_project_connections).
export const gcpProjectConnections = pgTable(
  'gcp_project_connections',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orgId: uuid('org_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
    projectId: uuid('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }),
    connectionId: uuid('connection_id').notNull().references(() => gcpConnections.id, { onDelete: 'cascade' }),
    createdByUserId: text('created_by_user_id'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('gcp_project_connections_project').on(t.projectId)],
);
export type GcpProjectConnection = typeof gcpProjectConnections.$inferSelect;

// Cloudflare credentials. projectId null = org-shared (reusable by any project);
// projectId set = project-owned standalone connection. Secrets are AES-GCM ciphertext.
export const cloudflareConnections = pgTable(
  'cloudflare_connections',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orgId: uuid('org_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
    projectId: uuid('project_id').references(() => projects.id, { onDelete: 'cascade' }), // null = org-shared
    name: text('name').notNull(),
    mode: text('mode').notNull(),                          // 'api_token' | 'global_key'
    secretCiphertext: text('secret_ciphertext').notNull(),
    metadata: jsonb('metadata').notNull().default(sql`'{}'::jsonb`), // { accountId?, accountName? }
    enabled: boolean('enabled').notNull().default(true),
    lastTestedAt: timestamp('last_tested_at', { withTimezone: true }),
    lastTestOk: boolean('last_test_ok'),
    createdByUserId: text('created_by_user_id'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('cloudflare_connections_org').on(t.orgId),
    uniqueIndex('cloudflare_connections_org_project_name').on(t.orgId, t.projectId, t.name),
  ],
);

export type CloudflareConnection = typeof cloudflareConnections.$inferSelect;

// One row per account/zone a project may query (its SCOPE), using a connection's creds.
export const cloudflareTargets = pgTable(
  'cloudflare_targets',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    projectId: uuid('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }),
    connectionId: uuid('connection_id').notNull().references(() => cloudflareConnections.id, { onDelete: 'cascade' }),
    kind: text('kind').notNull(),                          // 'account' | 'zone'
    accountId: text('account_id').notNull(),
    zoneId: text('zone_id'),
    name: text('name').notNull(),
    label: text('label'),
    workerScripts: jsonb('worker_scripts'),                // string[] | null (null/[] = all; account scope)
    metadata: jsonb('metadata').notNull().default(sql`'{}'::jsonb`), // { availableSignals }
    addedByUserId: text('added_by_user_id').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('cloudflare_targets_project_id').on(t.projectId),
    // coalesce(zone_id, '') so account rows (zone_id NULL) also collide — a plain
    // unique index treats NULLs as distinct, which let duplicate account scopes in.
    uniqueIndex('cloudflare_targets_project_scope').on(
      t.projectId, t.kind, t.accountId, sql`coalesce(${t.zoneId}, '')`,
    ),
  ],
);

export type CloudflareTarget = typeof cloudflareTargets.$inferSelect;

// A project's single Cloudflare connection binding. The project's "scope" (allowed
// resources) lives in cloudflare_targets; an empty scope means "query anything this
// connection can reach". This binding persists the connection even with no resources.
export const cloudflareProjectConnections = pgTable(
  'cloudflare_project_connections',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orgId: uuid('org_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
    projectId: uuid('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }),
    connectionId: uuid('connection_id').notNull().references(() => cloudflareConnections.id, { onDelete: 'cascade' }),
    createdByUserId: text('created_by_user_id'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('cloudflare_project_connections_project').on(t.projectId)],
);
export type CloudflareProjectConnection = typeof cloudflareProjectConnections.$inferSelect;

export const traces = pgTable(
  'traces',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orgId: uuid('org_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
    conversationId: uuid('conversation_id'),
    turnId: uuid('turn_id'),
    source: text('source').notNull().default('internal'),
    status: text('status').notNull().default('running'),
    startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(),
    endedAt: timestamp('ended_at', { withTimezone: true }),
    totalInputTokens: integer('total_input_tokens').notNull().default(0),
    totalOutputTokens: integer('total_output_tokens').notNull().default(0),
    totalCostUsd: numeric('total_cost_usd', { precision: 12, scale: 6 }).notNull().default('0'),
    modelCallCount: integer('model_call_count').notNull().default(0),
    toolCallCount: integer('tool_call_count').notNull().default(0),
    otelTraceId: text('otel_trace_id'),
  },
  (t) => [index('traces_conversation').on(t.conversationId), index('traces_org').on(t.orgId)],
);

export const traceSteps = pgTable(
  'trace_steps',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    traceId: uuid('trace_id').notNull().references(() => traces.id, { onDelete: 'cascade' }),
    type: text('type').notNull(),
    name: text('name').notNull(),
    status: text('status').notNull(),
    startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(),
    endedAt: timestamp('ended_at', { withTimezone: true }),
    latencyMs: integer('latency_ms'),
    inputTokens: integer('input_tokens'),
    outputTokens: integer('output_tokens'),
    costUsd: numeric('cost_usd', { precision: 12, scale: 6 }),
    error: text('error'),
    argsPreview: text('args_preview'),
    resultPreview: text('result_preview'),
    // Full tool I/O (capped at 1 MB by addTraceStep; truncated flag set when capped).
    args: text('args'),
    result: text('result'),
    truncated: boolean('truncated').notNull().default(false),
    childConversationId: uuid('child_conversation_id'),
  },
  (t) => [index('trace_steps_trace').on(t.traceId)],
);

export type Trace = typeof traces.$inferSelect;
export type TraceStep = typeof traceSteps.$inferSelect;

export const agentRuns = pgTable(
  'agent_runs',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    turnId: uuid('turn_id').notNull(),
    laneId: uuid('lane_id').notNull(),
    orgId: uuid('org_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
    status: text('status').notNull().default('suspended'), // suspended | approved | denied | resolved
    messages: jsonb('messages').$type<unknown>().notNull(),
    pendingCalls: jsonb('pending_calls').$type<unknown>().notNull(),
    // Per-call sub-agent results, accumulated as each delegated child finishes (sequential
    // fan-out): { [callId]: { result, childConversationId? } }. The parent resumes ONCE all
    // pending calls are present here — so a batch of parallel delegations all run and report.
    results: jsonb('results').$type<Record<string, { result: string; childConversationId?: string }>>().notNull().default({}),
    model: text('model').notNull(),
    enabledTools: jsonb('enabled_tools').$type<string[]>().notNull().default([]),
    slack: jsonb('slack').$type<unknown>(),
    otelTraceId: text('otel_trace_id'),
    depth: integer('depth').notNull().default(0),
    approvedBy: text('approved_by'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    resolvedAt: timestamp('resolved_at', { withTimezone: true }),
  },
  (t) => [index('agent_runs_lane').on(t.laneId), index('agent_runs_status').on(t.status)],
);
export type AgentRun = typeof agentRuns.$inferSelect;

export const mcpServers = pgTable(
  'mcp_servers',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orgId: uuid('org_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    url: text('url').notNull(),
    authType: text('auth_type').notNull().default('none'), // 'none' | 'bearer'
    secretCiphertext: text('secret_ciphertext'),
    enabled: boolean('enabled').notNull().default(true),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('mcp_servers_org_name').on(t.orgId, t.name), index('mcp_servers_org').on(t.orgId)],
);
export type McpServer = typeof mcpServers.$inferSelect;

// ── Code knowledge graph (built by apps/graph-builder; queried via repos/knowledge-graph) ──
export const kgBuilds = pgTable(
  'kg_builds',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orgId: uuid('org_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
    repoFullName: text('repo_full_name').notNull(),
    commitSha: text('commit_sha'),
    projectId: uuid('project_id'),
    phase: text('phase'),
    mode: text('mode').notNull(),                        // 'initial' | 'manual' | 'incremental'
    status: text('status').notNull().default('running'), // 'running' | 'done' | 'error'
    nodesAnalyzed: integer('nodes_analyzed').notNull().default(0),
    tokens: integer('tokens').notNull().default(0),
    costCredits: integer('cost_credits').notNull().default(0),
    truncated: boolean('truncated').notNull().default(false),
    note: text('note'),
    error: text('error'),
    startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(),
    finishedAt: timestamp('finished_at', { withTimezone: true }),
  },
  (t) => [
    index('kg_builds_org_repo').on(t.orgId, t.repoFullName),
    index('kg_builds_status').on(t.status),
    index('kg_builds_org_project_status').on(t.orgId, t.projectId, t.status),
  ],
);

export const kgNodes = pgTable(
  'kg_nodes',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orgId: uuid('org_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
    buildId: uuid('build_id').notNull().references(() => kgBuilds.id, { onDelete: 'cascade' }),
    repoFullName: text('repo_full_name').notNull(),
    kind: text('kind').notNull(),
    name: text('name').notNull(),
    businessFlow: text('business_flow'),
    digest: text('digest'),
    codeRefPath: text('code_ref_path'),
    codeRefStart: integer('code_ref_start'),
    codeRefEnd: integer('code_ref_end'),
    commitSha: text('commit_sha'),
    metadata: jsonb('metadata').$type<Record<string, unknown>>(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('kg_nodes_org_repo').on(t.orgId, t.repoFullName),
    index('kg_nodes_build').on(t.buildId),
    index('kg_nodes_build_kind').on(t.buildId, t.kind),
  ],
);

export const kgEdges = pgTable(
  'kg_edges',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orgId: uuid('org_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
    buildId: uuid('build_id').notNull().references(() => kgBuilds.id, { onDelete: 'cascade' }),
    srcNodeId: uuid('src_node_id').notNull().references(() => kgNodes.id, { onDelete: 'cascade' }),
    dstNodeId: uuid('dst_node_id').notNull().references(() => kgNodes.id, { onDelete: 'cascade' }),
    relation: text('relation').notNull(),
  },
  (t) => [
    index('kg_edges_src').on(t.srcNodeId),
    index('kg_edges_dst').on(t.dstNodeId),
    index('kg_edges_build').on(t.buildId),
  ],
);

export const kgNodeEmbeddings = pgTable('kg_node_embeddings', {
  nodeId: uuid('node_id').primaryKey().references(() => kgNodes.id, { onDelete: 'cascade' }),
  buildId: uuid('build_id').notNull().references(() => kgBuilds.id, { onDelete: 'cascade' }),
  embedding: vector('embedding', { dimensions: 768 }).notNull(),
});

export type KgBuild = typeof kgBuilds.$inferSelect;
export type KgNode = typeof kgNodes.$inferSelect;
export type KgEdge = typeof kgEdges.$inferSelect;
export type KgNodeEmbedding = typeof kgNodeEmbeddings.$inferSelect;

// ── Model invocation log (telemetry; best-effort write path) ──────────────────
export const modelInvocations = pgTable(
  'model_invocations',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orgId: uuid('org_id'),
    source: text('source').notNull(),
    model: text('model').notNull(),
    provider: text('provider'),
    conversationId: uuid('conversation_id'),
    buildId: uuid('build_id'),
    operationId: uuid('operation_id'),
    phase: text('phase'),
    messages: jsonb('messages').$type<unknown[]>(),
    output: text('output'),
    inputTokens: integer('input_tokens'),
    outputTokens: integer('output_tokens'),
    costUsd: numeric('cost_usd', { precision: 12, scale: 6 }),
    latencyMs: integer('latency_ms'),
    status: text('status').notNull(),
    error: text('error'),
    rateLimited: boolean('rate_limited').notNull().default(false),
    truncated: boolean('truncated').notNull().default(false),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('model_invocations_created').on(t.createdAt),
    index('model_invocations_source').on(t.source),
    index('model_invocations_model').on(t.model),
    index('model_invocations_org').on(t.orgId),
    index('model_invocations_operation').on(t.operationId),
  ],
);

export type ModelInvocation = typeof modelInvocations.$inferSelect;
export type NewModelInvocation = typeof modelInvocations.$inferInsert;

// ── Copilot issue offers (written by Slack RCA agent; consumed by Tasks 4+6) ──
// Soak-parity mirror — runtime reads from Firestore. Do NOT query this table in app code.
export const copilotIssueOffers = pgTable('copilot_issue_offers', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: uuid('org_id').notNull(),
  projectId: uuid('project_id').notNull(),
  conversationId: uuid('conversation_id').notNull(),
  slackChannelId: text('slack_channel_id').notNull(),
  slackThreadTs: text('slack_thread_ts').notNull(),
  slackMessageTs: text('slack_message_ts'),
  repo: text('repo'),
  candidateRepos: jsonb('candidate_repos').notNull().default(sql`'[]'::jsonb`),
  title: text('title').notNull(),
  body: text('body').notNull(),
  summary: text('summary').notNull(),
  status: text('status').notNull().default('offered'),
  issueNumber: integer('issue_number'),
  issueUrl: text('issue_url'),
  copilotAssigned: boolean('copilot_assigned').notNull().default(false),
  error: text('error'),
  decidedBy: text('decided_by'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  decidedAt: timestamp('decided_at', { withTimezone: true }),
});
